### ISSUE TITLE
paths-ignore not working

### ISSUE THREAD

**Issue by valentincastravete** [suo/flake8-github-action#13]
The **paths-ignore** option on GitHub action is not working on flake8 test. Should I set that option to flake8 test? If that's possible, how can I do that? Config file, as max-line-length issue? Thanks

This is my .yml file :

```
name: Flake8

on:
  push:
    paths-ignore:
      - '**__init__.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
