### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by acarl005** [suo/flake8-github-action#7]
Hello. My action is failing on the "Run flake8" step with the message `##[error]Cannot read property 'id' of undefined`.

Here is my workflow YAML

```yaml
name: Lint and Type Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - ci/lint-*

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64
      - uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: lint-and-type-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
